var express = require('express');
var bodyParser = require('body-parser');
var getfoodlistrouter =  require('./routes/getfoodlist.js');
var getIngredientlistrouter_a =  require('./routes/getIngredients_a.js');
var getIngredientlistrouter_b =  require('./routes/getIngredients_b.js');
var getIngredientlistrouter_c =  require('./routes/getIngredients_c.js');
var getIngredientlistrouter_d =  require('./routes/getIngredients_d.js');
var getIngredientlistrouter_e =  require('./routes/getIngredients_e.js');
var getIngredientlistrouter_f =  require('./routes/getIngredients_f.js');
var getIngredientlistrouter_g =  require('./routes/getIngredients_g.js');
var getIngredientlistrouter_h =  require('./routes/getIngredients_h.js');
var getIngredientlistrouter_i =  require('./routes/getIngredients_i.js');
var getIngredientlistrouter_j =  require('./routes/getIngredients_j.js');
var getIngredientlistrouter_k =  require('./routes/getIngredients_k.js');
var getIngredientlistrouter_l =  require('./routes/getIngredients_l.js');
var getIngredientlistrouter_m =  require('./routes/getIngredients_m.js');
var getIngredientlistrouter_n =  require('./routes/getIngredients_n.js');
var getIngredientlistrouter_o =  require('./routes/getIngredients_o.js');
var getIngredientlistrouter_p =  require('./routes/getIngredients_p.js');
var getIngredientlistrouter_q =  require('./routes/getIngredients_q.js');
var getIngredientlistrouter_r =  require('./routes/getIngredients_r.js');
var getIngredientlistrouter_s =  require('./routes/getIngredients_s.js');
var getIngredientlistrouter_t =  require('./routes/getIngredients_t.js');
var getIngredientlistrouter_u =  require('./routes/getIngredients_u.js');
var getIngredientlistrouter_v =  require('./routes/getIngredients_v.js');
var getIngredientlistrouter_w =  require('./routes/getIngredients_w.js');
var getIngredientlistrouter_x =  require('./routes/getIngredients_x.js');
var getIngredientlistrouter_y =  require('./routes/getIngredients_y.js');
var getIngredientlistrouter_z =  require('./routes/getIngredients_z.js');
var app = express();
var path = require('path');
var server = require('http').Server(app);
app.use(express.static(path.join(__dirname, 'public')));

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
  extended: true
}));
app.use('/api', getfoodlistrouter);
app.use('/api', getIngredientlistrouter_a);
app.use('/api', getIngredientlistrouter_b);
app.use('/api', getIngredientlistrouter_c);
app.use('/api', getIngredientlistrouter_d);
app.use('/api', getIngredientlistrouter_e);
app.use('/api', getIngredientlistrouter_f);
app.use('/api', getIngredientlistrouter_g);
app.use('/api', getIngredientlistrouter_h);
app.use('/api', getIngredientlistrouter_i);
app.use('/api', getIngredientlistrouter_j);
app.use('/api', getIngredientlistrouter_k);
app.use('/api', getIngredientlistrouter_l);
app.use('/api', getIngredientlistrouter_m);
app.use('/api', getIngredientlistrouter_n);
app.use('/api', getIngredientlistrouter_o);
app.use('/api', getIngredientlistrouter_p);
app.use('/api', getIngredientlistrouter_q);
app.use('/api', getIngredientlistrouter_r);
app.use('/api', getIngredientlistrouter_s);
app.use('/api', getIngredientlistrouter_t);
app.use('/api', getIngredientlistrouter_u);
app.use('/api', getIngredientlistrouter_v);
app.use('/api', getIngredientlistrouter_w);
app.use('/api', getIngredientlistrouter_x);
app.use('/api', getIngredientlistrouter_y);
app.use('/api', getIngredientlistrouter_z);
app.get('/index', function(req, res){
    res.json({'status':'success'});
});
app.get('/', function(req, res){
    res.json({'status':'success'});
});
app.listen(process.env.PORT || 3000, function () {
  console.log('Listening on port ' + 3000);
});
